/**
 * Dimension Template Generator
 * Converts html5up-dimension template into dynamic course template
 * Uses modal-style navigation with article-based content display
 */

import { CourseData, CourseConfig, CourseStage, ContentSection, ImageMetadata } from '@/types/course';
import { escapeHtml, generateInteractiveElement } from '../helpers';

export function generateDimensionTemplate(
  courseData: CourseData,
  config?: Partial<CourseConfig>
): string {
  const { course } = courseData;
  const totalStages = course.stages.length;
  const accent1 = config?.accentColor1 || '#4a90e2';
  const accent2 = config?.accentColor2 || '#50c9c3';

  // Generate navigation links for stages
  const navLinks = course.stages
    .map((stage) => `<li><a href="#stage-${stage.id}">${escapeHtml(stage.title)}</a></li>`)
    .join('\n\t\t\t\t\t');

  // Generate articles for each stage
  const articles = course.stages
    .map((stage) => generateStageArticle(stage))
    .join('\n\n\t\t\t\t\t');

  // Get CSS and JS
  const css = generateDimensionCSS(accent1, accent2);
  const noscriptCSS = generateDimensionNoscriptCSS();
  const js = generateDimensionJS();

  return `<!DOCTYPE HTML>
<html>
	<head>
		<title>${escapeHtml(course.title)}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
		<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300italic,600italic,300,600" rel="stylesheet">
		<style>
${css}
		</style>
		<noscript>
			<style>
${noscriptCSS}
			</style>
		</noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
		<div id="wrapper">

			<!-- Header -->
			<header id="header">
				<div class="logo">
					<span class="icon fa-gem"></span>
				</div>
				<div class="content">
					<div class="inner">
						<h1>${escapeHtml(course.title)}</h1>
						<p>${escapeHtml(course.description)}</p>
					</div>
				</div>
				<nav>
					<ul>
						${navLinks}
					</ul>
				</nav>
			</header>

			<!-- Main -->
			<div id="main">
				${articles}
			</div>

			<!-- Footer -->
			<footer id="footer">
				<p class="copyright">&copy; ${escapeHtml(course.title)}. Generated by ByteLab.</p>
			</footer>

		</div>

		<!-- BG -->
		<div id="bg"></div>

		<!-- Scripts -->
		<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
		<script>
			// Breakpoints library (embedded inline since CDN may not work)
			var breakpoints = function(){"use strict";function e(e){t.init(e)}var t={list:null,media:{},events:[],init:function(e){t.list=e,window.addEventListener("resize",t.poll),window.addEventListener("orientationchange",t.poll),window.addEventListener("load",t.poll),window.addEventListener("fullscreenchange",t.poll)},active:function(e){var n,a,s,i,r,d,c;if(!(e in t.media)){if(">="==e.substr(0,2)?(a="gte",n=e.substr(2)):"<="==e.substr(0,2)?(a="lte",n=e.substr(2)):">"==e.substr(0,1)?(a="gt",n=e.substr(1)):"<"==e.substr(0,1)?(a="lt",n=e.substr(1)):"!"==e.substr(0,1)?(a="not",n=e.substr(1)):(a="eq",n=e),n&&n in t.list)if(i=t.list[n],Array.isArray(i)){if(r=parseInt(i[0]),d=parseInt(i[1]),isNaN(r)){if(isNaN(d))return;c=i[1].substr(String(d).length)}else c=i[0].substr(String(r).length);if(isNaN(r))switch(a){case"gte":s="screen";break;case"lte":s="screen and (max-width: "+d+c+")";break;case"gt":s="screen and (min-width: "+(d+1)+c+")";break;case"lt":s="screen and (max-width: -1px)";break;case"not":s="screen and (min-width: "+(d+1)+c+")";break;default:s="screen and (max-width: "+d+c+")"}else if(isNaN(d))switch(a){case"gte":s="screen and (min-width: "+r+c+")";break;case"lte":s="screen";break;case"gt":s="screen and (max-width: -1px)";break;case"lt":s="screen and (max-width: "+(r-1)+c+")";break;case"not":s="screen and (max-width: "+(r-1)+c+")";break;default:s="screen and (min-width: "+r+c+")"}else switch(a){case"gte":s="screen and (min-width: "+r+c+")";break;case"lte":s="screen and (max-width: "+d+c+")";break;case"gt":s="screen and (min-width: "+(d+1)+c+")";break;case"lt":s="screen and (max-width: "+(r-1)+c+")";break;case"not":s="screen and (max-width: "+(r-1)+c+"), screen and (min-width: "+(d+1)+c+")";break;default:s="screen and (min-width: "+r+c+") and (max-width: "+d+c+")"}}else s="("==i.charAt(0)?"screen and "+i:i;t.media[e]=!!s&&s}return t.media[e]!==!1&&window.matchMedia(t.media[e]).matches},on:function(e,n){t.events.push({query:e,handler:n,state:!1}),t.active(e)&&n()},poll:function(){var e,n;for(e=0;e<t.events.length;e++)n=t.events[e],t.active(n.query)?n.state||(n.state=!0,n.handler()):n.state&&(n.state=!1)}};return e._=t,e.on=function(e,n){t.on(e,n)},e.active=function(e){return t.active(e)},e}();
		</script>
		<script>
			// Browser detection
			var browser = (function() {
				var ua = navigator.userAgent;
				var browser = { name: 'other', version: null, os: 'other', osVersion: null, touch: false, mobile: false };
				if (ua.match(/Chrome\\/([0-9\\.]+)/)) { browser.name = 'chrome'; browser.version = parseFloat(RegExp.$1); }
				else if (ua.match(/Firefox\\/([0-9\\.]+)/)) { browser.name = 'firefox'; browser.version = parseFloat(RegExp.$1); }
				else if (ua.match(/Safari\\/([0-9\\.]+)/)) { browser.name = 'safari'; browser.version = parseFloat(RegExp.$1); }
				else if (ua.match(/MSIE ([0-9]+)/) || ua.match(/Trident\\/.+rv:([0-9]+)/)) { browser.name = 'ie'; browser.version = parseFloat(RegExp.$1); }
				if ('ontouchstart' in window) browser.touch = true;
				if (/Android|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(ua)) browser.mobile = true;
				return browser;
			})();
		</script>
		<script>
			// Util functions
			(function($) {
				$.fn.navList = function() {
					var $this = $(this), $a = $this.find('a'), b = [];
					$a.each(function() {
						var $this = $(this), indent = Math.max(0, $this.parents('li').length - 1), href = $this.attr('href'), target = $this.attr('target');
						b.push('<a class="link depth-' + indent + '"' + (typeof target !== 'undefined' && target != '' ? ' target="' + target + '"' : '') + (typeof href !== 'undefined' && href != '' ? ' href="' + href + '"' : '') + '><span class="indent-' + indent + '"></span>' + $this.text() + '</a>');
					});
					return b.join('');
				};
			})(jQuery);
		</script>
		<script>
${js}
		</script>
		<script>
			// Fallback: Remove is-preload class if JavaScript fails
			window.addEventListener('load', function() {
				setTimeout(function() {
					document.body.classList.remove('is-preload');
				}, 200);
			});
			// Also remove immediately if DOM is already loaded
			if (document.readyState === 'complete' || document.readyState === 'interactive') {
				setTimeout(function() {
					document.body.classList.remove('is-preload');
				}, 1);
			}

			// Interactive Elements JavaScript
			(function() {
				// Quiz functionality
				document.addEventListener('click', function(e) {
					if (e.target.classList.contains('choice')) {
						var question = e.target.closest('.quiz-question');
						if (!question) return;
						
						// Don't allow re-selection if already answered
						if (question.classList.contains('answered')) return;
						
						// Remove previous selections in this question
						question.querySelectorAll('.choice').forEach(function(choice) {
							choice.classList.remove('selected', 'correct', 'incorrect');
						});
						
						// Mark this choice as selected
						e.target.classList.add('selected');
						
						// Get correct answer from data attribute or default to first option
						var correctAnswer = question.getAttribute('data-correct');
						if (!correctAnswer) {
							// Try to get from first option if no data attribute
							var firstChoice = question.querySelector('.choice');
							correctAnswer = firstChoice ? firstChoice.getAttribute('data-value') : 'A';
						}
						
						var selectedValue = e.target.getAttribute('data-value');
						
						// Mark question as answered
						question.classList.add('answered');
						
						if (selectedValue === correctAnswer) {
							e.target.classList.add('correct');
							var explanation = question.querySelector('.quiz-explanation');
							if (explanation) {
								explanation.style.display = 'block';
							}
						} else {
							e.target.classList.add('incorrect');
							// Show correct answer
							question.querySelectorAll('.choice').forEach(function(choice) {
								if (choice.getAttribute('data-value') === correctAnswer) {
									choice.classList.add('correct');
								}
							});
							var explanation = question.querySelector('.quiz-explanation');
							if (explanation) {
								explanation.style.display = 'block';
							}
						}
					}
				});

				// Expandable functionality
				window.toggleExpand = function(header, event) {
					if (event) {
						event.preventDefault();
						event.stopPropagation();
					}
					var section = header.closest('.expandable-section');
					if (section) {
						section.classList.toggle('expanded');
					}
				};

				// Matching functionality
				var selectedMatch = null;
				window.selectMatch = function(element, idx, event) {
					if (event) {
						event.preventDefault();
						event.stopPropagation();
					}
					if (element.classList.contains('matched')) return;
					
					if (selectedMatch) {
						selectedMatch.classList.remove('selected');
					}
					element.classList.add('selected');
					selectedMatch = element;
				};

				window.matchWith = function(element, idx, event) {
					if (event) {
						event.preventDefault();
						event.stopPropagation();
					}
					if (element.classList.contains('matched')) return;
					
					if (selectedMatch && selectedMatch.getAttribute('data-side') === 'left') {
						// Simple matching logic - you can enhance this
						selectedMatch.classList.remove('selected');
						selectedMatch.classList.add('matched');
						element.classList.add('matched');
						selectedMatch = null;
					}
				};
			})();
		</script>

	</body>
</html>`;
}

/**
 * Generates an article element for a course stage
 */
function generateStageArticle(stage: CourseStage): string {
  const content = stage.content || { introduction: '', sections: [], summary: '' };
  
  // Generate introduction
  const introduction = content.introduction
    ? `<p>${escapeHtml(content.introduction)}</p>`
    : '';
  
  // Generate objective
  const objective = stage.objective
    ? `<p><strong>Learning Objective:</strong> ${escapeHtml(stage.objective)}</p>`
    : '';
  
  // Generate sections
  const sections = content.sections
    ? content.sections.map(section => generateSection(section)).join('\n\t\t\t\t\t')
    : '';
  
  // Generate interactive elements
  const interactiveElements = stage.interactiveElements
    ? stage.interactiveElements.map(element => generateInteractiveElement(element, stage.id)).join('\n\t\t\t\t\t')
    : '';
  
  // Generate quiz questions
  const quizQuestions = stage.quizQuestions && stage.quizQuestions.length > 0
    ? `<hr /><h3>Quiz Questions</h3>${stage.quizQuestions.map((q, idx) => {
        const options = q.options || [];
        const optionsHtml = options
          .map((opt: string, optIdx: number) => {
            const letter = String.fromCharCode(65 + optIdx);
            return `<span class="choice" data-value="${letter}">${escapeHtml(opt)}</span>`;
          })
          .join('\n\t\t\t\t\t\t\t');
        
        // Get correct answer letter
        const correctAnswer = q.correctAnswer || 'A';
        const correctIndex = typeof correctAnswer === 'number' ? correctAnswer : (correctAnswer.charCodeAt(0) - 65);
        const correctLetter = typeof correctAnswer === 'string' && correctAnswer.length === 1 
          ? correctAnswer 
          : String.fromCharCode(65 + (correctIndex >= 0 && correctIndex < options.length ? correctIndex : 0));
        
        return `<div class="quiz-question" data-qid="quiz-${stage.id}-${idx}" data-correct="${correctLetter}">
						<strong>${idx + 1}. ${escapeHtml(q.question)}</strong><br>
						<div class="quiz-options">
							${optionsHtml}
						</div>
						${q.explanation ? `<div class="quiz-explanation" style="display: none; margin-top: 10px; padding: 10px; background: rgba(0,0,0,0.1); border-radius: 5px;">${escapeHtml(q.explanation)}</div>` : ''}
					</div>`;
      }).join('\n\t\t\t\t\t')}`
    : '';
  
  // Generate summary
  const summary = content.summary
    ? `<hr /><h3>Summary</h3><p>${escapeHtml(content.summary)}</p>`
    : '';
  
  // Get first image for main image if available
  const firstImage = content.sections?.find(s => s.image)?.image as ImageMetadata | undefined;
  const mainImage = firstImage
    ? `<span class="image main"><img src="${escapeHtml(firstImage.url)}" alt="${escapeHtml(stage.title)}" /></span>`
    : '';
  
  return `<!-- Stage ${stage.id} -->
				<article id="stage-${stage.id}">
					<h2 class="major">${escapeHtml(stage.title)}</h2>
					${mainImage}
					${introduction}
					${objective}
					${sections}
					${interactiveElements}
					${quizQuestions}
					${summary}
				</article>`;
}

/**
 * Generates HTML for a content section
 */
function generateSection(section: ContentSection): string {
  let html = '';
  
  if (section.heading) {
    html += `<h3>${escapeHtml(section.heading)}</h3>`;
  }
  
  if (section.content) {
    html += `<p>${escapeHtml(section.content)}</p>`;
  }
  
  if (section.image) {
    const image = section.image as ImageMetadata;
    const mediaType = image.mediaType || 'image';
    const isVideoLoop = mediaType === 'video-loop' || (image.loop && image.autoplay);
    
    if (isVideoLoop) {
      html += `<span class="image main">
        <video src="${escapeHtml(image.url)}" 
               alt="${escapeHtml(section.heading || '')}" 
               style="width:100%;height:auto;border-radius:4px;"
               loop autoplay muted playsinline />
        ${image.attribution ? `<p style="font-size:0.8rem;margin-top:0.5rem;opacity:0.75;">${escapeHtml(image.attribution)}</p>` : ''}
      </span>`;
    } else {
      html += `<span class="image main">
        <img src="${escapeHtml(image.url)}" 
             alt="${escapeHtml(section.heading || image.attribution || '')}" />
        ${image.attribution ? `<p style="font-size:0.8rem;margin-top:0.5rem;opacity:0.75;">${escapeHtml(image.attribution)}</p>` : ''}
      </span>`;
    }
  }
  
  if (section.type === 'list' && section.items && section.items.length > 0) {
    html += '<ul>';
    section.items.forEach(item => {
      html += `<li>${escapeHtml(item)}</li>`;
    });
    html += '</ul>';
  }
  
  return html;
}

/**
 * Generates CSS for dimension template
 * Embeds the full CSS from main.css with color customization
 */
function generateDimensionCSS(accent1: string, accent2: string): string {
  // Read the CSS file content - we'll embed it
  // Note: In production, this would be embedded at build time
  // For now, we'll use the CSS content from the copied file
  // The CSS is embedded as a template string - we need to escape backticks
  const cssContent = `/* Dimension Template CSS - Full CSS embedded */
		/* Note: @import statements removed - using CDN for FontAwesome */
		
		html, body, div, span, applet, object,
		iframe, h1, h2, h3, h4, h5, h6, p, blockquote,
		pre, a, abbr, acronym, address, big, cite,
		code, del, dfn, em, img, ins, kbd, q, s, samp,
		small, strike, strong, sub, sup, tt, var, b,
		u, i, center, dl, dt, dd, ol, ul, li, fieldset,
		form, label, legend, table, caption, tbody,
		tfoot, thead, tr, th, td, article, aside,
		canvas, details, embed, figure, figcaption,
		footer, header, hgroup, menu, nav, output, ruby,
		section, summary, time, mark, audio, video {
			margin: 0;
			padding: 0;
			border: 0;
			font-size: 100%;
			font: inherit;
			vertical-align: baseline;
		}

		article, aside, details, figcaption, figure,
		footer, header, hgroup, menu, nav, section {
			display: block;
		}

		body {
			line-height: 1;
		}

		ol, ul {
			list-style: none;
		}

		blockquote, q {
			quotes: none;
		}

			blockquote:before, blockquote:after, q:before, q:after {
				content: '';
				content: none;
			}

		table {
			border-collapse: collapse;
			border-spacing: 0;
		}

		body {
			-webkit-text-size-adjust: none;
		}

		mark {
			background-color: transparent;
			color: inherit;
		}

		input::-moz-focus-inner {
			border: 0;
			padding: 0;
		}

		input, select, textarea {
			-moz-appearance: none;
			-webkit-appearance: none;
			-ms-appearance: none;
			appearance: none;
		}

		/* Basic */

			@-ms-viewport {
				width: device-width;
			}

			@media screen and (max-width: 480px) {

				html, body {
					min-width: 320px;
				}

			}

			html {
				box-sizing: border-box;
			}

			*, *:before, *:after {
				box-sizing: inherit;
			}

			body {
				background: #1b1f22;
			}

				body.is-preload *, body.is-preload *:before, body.is-preload *:after {
					-moz-animation: none !important;
					-webkit-animation: none !important;
					-ms-animation: none !important;
					animation: none !important;
					-moz-transition: none !important;
					-webkit-transition: none !important;
					-ms-transition: none !important;
					transition: none !important;
				}

		/* Type */

			html {
				font-size: 16pt;
			}

				@media screen and (max-width: 1680px) {

					html {
						font-size: 12pt;
					}

				}

				@media screen and (max-width: 736px) {

					html {
						font-size: 11pt;
					}

				}

				@media screen and (max-width: 360px) {

					html {
						font-size: 10pt;
					}

				}

			body, input, select, textarea {
				color: #ffffff;
				font-family: "Source Sans Pro", sans-serif;
				font-weight: 300;
				font-size: 1rem;
				line-height: 1.65;
			}

			a {
				-moz-transition: color 0.2s ease-in-out, background-color 0.2s ease-in-out, border-bottom-color 0.2s ease-in-out;
				-webkit-transition: color 0.2s ease-in-out, background-color 0.2s ease-in-out, border-bottom-color 0.2s ease-in-out;
				-ms-transition: color 0.2s ease-in-out, background-color 0.2s ease-in-out, border-bottom-color 0.2s ease-in-out;
				transition: color 0.2s ease-in-out, background-color 0.2s ease-in-out, border-bottom-color 0.2s ease-in-out;
				border-bottom: dotted 1px rgba(255, 255, 255, 0.5);
				text-decoration: none;
				color: inherit;
			}

				a:hover {
					border-bottom-color: transparent;
				}

			strong, b {
				color: #ffffff;
				font-weight: 600;
			}

			em, i {
				font-style: italic;
			}

			p {
				margin: 0 0 2rem 0;
			}

			h1, h2, h3, h4, h5, h6 {
				color: #ffffff;
				font-weight: 600;
				line-height: 1.5;
				margin: 0 0 1rem 0;
				text-transform: uppercase;
				letter-spacing: 0.2rem;
			}

				h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {
					color: inherit;
					text-decoration: none;
				}

				h1.major, h2.major, h3.major, h4.major, h5.major, h6.major {
					border-bottom: solid 1px #ffffff;
					width: -moz-max-content;
					width: -webkit-max-content;
					width: -ms-max-content;
					width: max-content;
					padding-bottom: 0.5rem;
					margin: 0 0 2rem 0;
				}

			h1 {
				font-size: 2.25rem;
				line-height: 1.3;
				letter-spacing: 0.5rem;
			}

			h2 {
				font-size: 1.5rem;
				line-height: 1.4;
				letter-spacing: 0.5rem;
			}

			h3 {
				font-size: 1rem;
			}

			h4 {
				font-size: 0.8rem;
			}

			h5 {
				font-size: 0.7rem;
			}

			h6 {
				font-size: 0.6rem;
			}

			@media screen and (max-width: 736px) {

				h1 {
					font-size: 1.75rem;
					line-height: 1.4;
				}

				h2 {
					font-size: 1.25em;
					line-height: 1.5;
				}

			}

			sub {
				font-size: 0.8rem;
				position: relative;
				top: 0.5rem;
			}

			sup {
				font-size: 0.8rem;
				position: relative;
				top: -0.5rem;
			}

			blockquote {
				border-left: solid 4px #ffffff;
				font-style: italic;
				margin: 0 0 2rem 0;
				padding: 0.5rem 0 0.5rem 2rem;
			}

			code {
				background: rgba(255, 255, 255, 0.075);
				border-radius: 4px;
				font-family: "Courier New", monospace;
				font-size: 0.9rem;
				margin: 0 0.25rem;
				padding: 0.25rem 0.65rem;
			}

			pre {
				-webkit-overflow-scrolling: touch;
				font-family: "Courier New", monospace;
				font-size: 0.9rem;
				margin: 0 0 2rem 0;
			}

				pre code {
					display: block;
					line-height: 1.75;
					padding: 1rem 1.5rem;
					overflow-x: auto;
				}

			hr {
				border: 0;
				border-bottom: solid 1px #ffffff;
				margin: 2.75rem 0;
			}

			.align-left {
				text-align: left;
			}

			.align-center {
				text-align: center;
			}

			.align-right {
				text-align: right;
			}

		/* Form - styles continue... */
		/* Full CSS continues - see _dimensionCSS.txt for complete styles */
		/* For brevity, including key styles above - full CSS would be embedded here */
		
		/* Icon */
		.icon {
			text-decoration: none;
			border-bottom: none;
			position: relative;
		}

			.icon:before {
				-moz-osx-font-smoothing: grayscale;
				-webkit-font-smoothing: antialiased;
				display: inline-block;
				font-style: normal;
				font-variant: normal;
				text-rendering: auto;
				line-height: 1;
				text-transform: none !important;
				font-family: 'Font Awesome 5 Free';
				font-weight: 400;
			}

			.icon > .label {
				display: none;
			}

			.icon:before {
				line-height: inherit;
			}

			.icon.solid:before {
				font-weight: 900;
			}

			.icon.brands:before {
				font-family: 'Font Awesome 5 Brands';
			}

		/* Image */
		.image {
			border-radius: 4px;
			border: 0;
			display: inline-block;
			position: relative;
		}

			.image:before {
				pointer-events: none;
				background-color: rgba(19, 21, 25, 0.5);
				border-radius: 4px;
				content: '';
				display: block;
				height: 100%;
				left: 0;
				opacity: 0.5;
				position: absolute;
				top: 0;
				width: 100%;
			}

			.image img {
				border-radius: 4px;
				display: block;
			}

			.image.main {
				display: block;
				margin: 2.5rem 0;
				width: 100%;
			}

				.image.main img {
					width: 100%;
				}

		/* List */
		ol {
			list-style: decimal;
			margin: 0 0 2rem 0;
			padding-left: 1.25em;
		}

			ol li {
				padding-left: 0.25em;
			}

		ul {
			list-style: disc;
			margin: 0 0 2rem 0;
			padding-left: 1em;
		}

			ul li {
				padding-left: 0.5em;
			}

		/* Button */
		input[type="submit"],
		input[type="reset"],
		input[type="button"],
		button,
		.button {
			-moz-appearance: none;
			-webkit-appearance: none;
			-ms-appearance: none;
			appearance: none;
			-moz-transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out;
			-webkit-transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out;
			-ms-transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out;
			transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out;
			background-color: transparent;
			border-radius: 4px;
			border: 0;
			box-shadow: inset 0 0 0 1px #ffffff;
			color: #ffffff !important;
			cursor: pointer;
			display: inline-block;
			font-size: 0.8rem;
			font-weight: 300;
			height: 2.75rem;
			letter-spacing: 0.2rem;
			line-height: 2.75rem;
			outline: 0;
			padding: 0 1.25rem 0 1.35rem;
			text-align: center;
			text-decoration: none;
			text-transform: uppercase;
			white-space: nowrap;
		}

			input[type="submit"]:hover,
			input[type="reset"]:hover,
			input[type="button"]:hover,
			button:hover,
			.button:hover {
				background-color: rgba(255, 255, 255, 0.075);
			}

			input[type="submit"].primary,
			input[type="reset"].primary,
			input[type="button"].primary,
			button.primary,
			.button.primary {
				background-color: #ffffff;
				color: #1b1f22 !important;
				font-weight: 600;
			}

		/* BG */
		#bg {
			-moz-transform: scale(1.0);
			-webkit-transform: scale(1.0);
			-ms-transform: scale(1.0);
			transform: scale(1.0);
			-webkit-backface-visibility: hidden;
			position: fixed;
			top: 0;
			left: 0;
			width: 100%;
			height: 100vh;
			z-index: 1;
		}

			#bg:before, #bg:after {
				content: '';
				display: block;
				position: absolute;
				top: 0;
				left: 0;
				width: 100%;
				height: 100%;
			}

			#bg:before {
				-moz-transition: background-color 2.5s ease-in-out;
				-webkit-transition: background-color 2.5s ease-in-out;
				-ms-transition: background-color 2.5s ease-in-out;
				transition: background-color 2.5s ease-in-out;
				-moz-transition-delay: 0.75s;
				-webkit-transition-delay: 0.75s;
				-ms-transition-delay: 0.75s;
				transition-delay: 0.75s;
				background-image: linear-gradient(to top, rgba(19, 21, 25, 0.5), rgba(19, 21, 25, 0.5));
				background-size: auto, 256px 256px;
				background-position: center, center;
				background-repeat: no-repeat, repeat;
				z-index: 2;
			}

			#bg:after {
				-moz-transform: scale(1.125);
				-webkit-transform: scale(1.125);
				-ms-transform: scale(1.125);
				transform: scale(1.125);
				-moz-transition: -moz-transform 0.325s ease-in-out, -moz-filter 0.325s ease-in-out;
				-webkit-transition: -webkit-transform 0.325s ease-in-out, -webkit-filter 0.325s ease-in-out;
				-ms-transition: -ms-transform 0.325s ease-in-out, -ms-filter 0.325s ease-in-out;
				transition: transform 0.325s ease-in-out, filter 0.325s ease-in-out;
				background-color: #1b1f22;
				background-image: linear-gradient(135deg, ${accent1}20 0%, ${accent2}20 50%, #1b1f22 100%);
				background-position: center;
				background-size: cover;
				background-repeat: no-repeat;
				z-index: 1;
			}

			body.is-article-visible #bg:after {
				-moz-transform: scale(1.0825);
				-webkit-transform: scale(1.0825);
				-ms-transform: scale(1.0825);
				transform: scale(1.0825);
				-moz-filter: blur(0.2rem);
				-webkit-filter: blur(0.2rem);
				-ms-filter: blur(0.2rem);
				filter: blur(0.2rem);
			}

			body.is-preload #bg:before {
				background-color: rgba(19, 21, 25, 0.8);
			}

		/* Wrapper */
		#wrapper {
			display: -moz-flex;
			display: -webkit-flex;
			display: -ms-flex;
			display: flex;
			-moz-flex-direction: column;
			-webkit-flex-direction: column;
			-ms-flex-direction: column;
			flex-direction: column;
			-moz-align-items: center;
			-webkit-align-items: center;
			-ms-align-items: center;
			align-items: center;
			-moz-justify-content: space-between;
			-webkit-justify-content: space-between;
			-ms-justify-content: space-between;
			justify-content: space-between;
			position: relative;
			min-height: 100vh;
			width: 100%;
			padding: 4rem 2rem;
			z-index: 3;
		}

			#wrapper:before {
				content: '';
				display: block;
			}

			@media screen and (max-width: 1680px) {

				#wrapper {
					padding: 3rem 2rem;
				}

			}

			@media screen and (max-width: 736px) {

				#wrapper {
					padding: 2rem 1rem;
				}

			}

			@media screen and (max-width: 480px) {

				#wrapper {
					padding: 1rem;
				}

			}

		/* Header */
		#header {
			display: -moz-flex;
			display: -webkit-flex;
			display: -ms-flex;
			display: flex;
			-moz-flex-direction: column;
			-webkit-flex-direction: column;
			-ms-flex-direction: column;
			flex-direction: column;
			-moz-align-items: center;
			-webkit-align-items: center;
			-ms-align-items: center;
			align-items: center;
			-moz-transition: -moz-transform 0.325s ease-in-out, -moz-filter 0.325s ease-in-out, opacity 0.325s ease-in-out;
			-webkit-transition: -webkit-transform 0.325s ease-in-out, -webkit-filter 0.325s ease-in-out, opacity 0.325s ease-in-out;
			-ms-transition: -ms-transform 0.325s ease-in-out, -ms-filter 0.325s ease-in-out, opacity 0.325s ease-in-out;
			transition: transform 0.325s ease-in-out, filter 0.325s ease-in-out, opacity 0.325s ease-in-out;
			background-image: -moz-radial-gradient(rgba(0, 0, 0, 0.25) 25%, rgba(0, 0, 0, 0) 55%);
			background-image: -webkit-radial-gradient(rgba(0, 0, 0, 0.25) 25%, rgba(0, 0, 0, 0) 55%);
			background-image: -ms-radial-gradient(rgba(0, 0, 0, 0.25) 25%, rgba(0, 0, 0, 0) 55%);
			background-image: radial-gradient(rgba(0, 0, 0, 0.25) 25%, rgba(0, 0, 0, 0) 55%);
			max-width: 100%;
			text-align: center;
		}

			#header > * {
				-moz-transition: opacity 0.325s ease-in-out;
				-webkit-transition: opacity 0.325s ease-in-out;
				-ms-transition: opacity 0.325s ease-in-out;
				transition: opacity 0.325s ease-in-out;
				position: relative;
				margin-top: 3.5rem;
			}

				#header > *:before {
					content: '';
					display: block;
					position: absolute;
					top: calc(-3.5rem - 1px);
					left: calc(50% - 1px);
					width: 1px;
					height: calc(3.5rem + 1px);
					background: #ffffff;
				}

			#header > :first-child {
				margin-top: 0;
			}

				#header > :first-child:before {
					display: none;
				}

			#header .logo {
				width: 5.5rem;
				height: 5.5rem;
				line-height: 5.5rem;
				border: solid 1px #ffffff;
				border-radius: 100%;
			}

				#header .logo .icon:before {
					font-size: 2rem;
				}

			#header .content {
				border-style: solid;
				border-color: #ffffff;
				border-top-width: 1px;
				border-bottom-width: 1px;
				max-width: 100%;
			}

				#header .content .inner {
					-moz-transition: max-height 0.75s ease, padding 0.75s ease, opacity 0.325s ease-in-out;
					-webkit-transition: max-height 0.75s ease, padding 0.75s ease, opacity 0.325s ease-in-out;
					-ms-transition: max-height 0.75s ease, padding 0.75s ease, opacity 0.325s ease-in-out;
					transition: max-height 0.75s ease, padding 0.75s ease, opacity 0.325s ease-in-out;
					-moz-transition-delay: 0.25s;
					-webkit-transition-delay: 0.25s;
					-ms-transition-delay: 0.25s;
					transition-delay: 0.25s;
					padding: 3rem 2rem;
					max-height: 40rem;
					overflow: hidden;
				}

					#header .content .inner > :last-child {
						margin-bottom: 0;
					}

				#header .content p {
					text-transform: uppercase;
					letter-spacing: 0.2rem;
					font-size: 0.8rem;
					line-height: 2;
				}

			#header nav ul {
				display: -moz-flex;
				display: -webkit-flex;
				display: -ms-flex;
				display: flex;
				margin-bottom: 0;
				list-style: none;
				padding-left: 0;
				border: solid 1px #ffffff;
				border-radius: 4px;
			}

				#header nav ul li {
					padding-left: 0;
					border-left: solid 1px #ffffff;
				}

					#header nav ul li:first-child {
						border-left: 0;
					}

					#header nav ul li a {
						display: block;
						min-width: 7.5rem;
						height: 2.75rem;
						line-height: 2.75rem;
						padding: 0 1.25rem 0 1.45rem;
						text-transform: uppercase;
						letter-spacing: 0.2rem;
						font-size: 0.8rem;
						border-bottom: 0;
					}

						#header nav ul li a:hover {
							background-color: rgba(255, 255, 255, 0.075);
						}

						#header nav ul li a:active {
							background-color: rgba(255, 255, 255, 0.175);
						}

			#header nav.use-middle:after {
				content: '';
				display: block;
				position: absolute;
				top: 0;
				left: calc(50% - 1px);
				width: 1px;
				height: 100%;
				background: #ffffff;
			}

			#header nav.use-middle ul li.is-middle {
				border-left: 0;
			}

			body.is-article-visible #header {
				-moz-transform: scale(0.95);
				-webkit-transform: scale(0.95);
				-ms-transform: scale(0.95);
				transform: scale(0.95);
				-moz-filter: blur(0.1rem);
				-webkit-filter: blur(0.1rem);
				-ms-filter: blur(0.1rem);
				filter: blur(0.1rem);
				opacity: 0;
			}

			body.is-preload #header {
				-moz-filter: blur(0.125rem);
				-webkit-filter: blur(0.125rem);
				-ms-filter: blur(0.125rem);
				filter: blur(0.125rem);
			}

				body.is-preload #header > * {
					opacity: 0.3;
				}

				body.is-preload #header .content .inner {
					max-height: 40rem;
					padding: 3rem 2rem;
					opacity: 0.3;
				}

			@media screen and (max-width: 980px) {

				#header .content p br {
					display: none;
				}

			}

			@media screen and (max-width: 736px) {

				#header > * {
					margin-top: 2rem;
				}

					#header > *:before {
						top: calc(-2rem - 1px);
						height: calc(2rem + 1px);
					}

				#header .logo {
					width: 4.75rem;
					height: 4.75rem;
					line-height: 4.75rem;
				}

					#header .logo .icon:before {
						font-size: 1.75rem;
					}

				#header .content .inner {
					padding: 2.5rem 1rem;
				}

				#header .content p {
					line-height: 1.875;
				}

			}

			@media screen and (max-width: 480px) {

				#header {
					padding: 1.5rem 0;
				}

					#header .content .inner {
						padding: 2.5rem 0;
					}

					#header nav ul {
						-moz-flex-direction: column;
						-webkit-flex-direction: column;
						-ms-flex-direction: column;
						flex-direction: column;
						min-width: 10rem;
						max-width: 100%;
					}

						#header nav ul li {
							border-left: 0;
							border-top: solid 1px #ffffff;
						}

							#header nav ul li:first-child {
								border-top: 0;
							}

							#header nav ul li a {
								height: 3rem;
								line-height: 3rem;
								min-width: 0;
								width: 100%;
							}

					#header nav.use-middle:after {
						display: none;
					}

			}

		/* Main */
		#main {
			-moz-flex-grow: 1;
			-webkit-flex-grow: 1;
			-ms-flex-grow: 1;
			flex-grow: 1;
			-moz-flex-shrink: 1;
			-webkit-flex-shrink: 1;
			-ms-flex-shrink: 1;
			flex-shrink: 1;
			display: -moz-flex;
			display: -webkit-flex;
			display: -ms-flex;
			display: flex;
			-moz-align-items: center;
			-webkit-align-items: center;
			-ms-align-items: center;
			align-items: center;
			-moz-justify-content: center;
			-webkit-justify-content: center;
			-ms-justify-content: center;
			justify-content: center;
			-moz-flex-direction: column;
			-webkit-flex-direction: column;
			-ms-flex-direction: column;
			flex-direction: column;
			position: relative;
			max-width: 100%;
			z-index: 3;
			cursor: default;
		}
		
		/* Make #main backdrop clickable when article is visible */
		body.is-article-visible #main {
			cursor: pointer;
		}
		
		body.is-article-visible #main article {
			cursor: default;
			pointer-events: auto;
		}

			#main article {
				-moz-transform: translateY(0.25rem);
				-webkit-transform: translateY(0.25rem);
				-ms-transform: translateY(0.25rem);
				transform: translateY(0.25rem);
				-moz-transition: opacity 0.325s ease-in-out, -moz-transform 0.325s ease-in-out;
				-webkit-transition: opacity 0.325s ease-in-out, -webkit-transform 0.325s ease-in-out;
				-ms-transition: opacity 0.325s ease-in-out, -ms-transform 0.325s ease-in-out;
				transition: opacity 0.325s ease-in-out, transform 0.325s ease-in-out;
				padding: 4.5rem 3rem 2rem 3rem !important;
				position: relative;
				width: 90% !important;
				max-width: 70rem !important;
				min-width: 50rem !important;
				background-color: rgba(27, 31, 34, 0.95);
				border-radius: 12px;
				box-shadow: 0 10px 40px rgba(0, 0, 0, 0.5);
				opacity: 0;
				overflow-y: auto;
				max-height: 90vh;
			}

				@media screen and (max-width: 1200px) {
					#main article {
						width: 85% !important;
						max-width: 60rem !important;
						min-width: 45rem !important;
					}
				}

				@media screen and (max-width: 900px) {
					#main article {
						width: 90% !important;
						max-width: 100% !important;
						min-width: 0 !important;
					}
				}

				#main article.active {
					-moz-transform: translateY(0);
					-webkit-transform: translateY(0);
					-ms-transform: translateY(0);
					transform: translateY(0);
					opacity: 1;
				}

				#main article .close {
					display: block;
					position: absolute;
					top: 1rem;
					right: 1rem;
					width: 3rem;
					height: 3rem;
					cursor: pointer;
					text-indent: 3rem;
					overflow: hidden;
					white-space: nowrap;
					z-index: 10;
					pointer-events: auto !important;
				}

					#main article .close:before {
						-moz-transition: background-color 0.2s ease-in-out, transform 0.2s ease-in-out;
						-webkit-transition: background-color 0.2s ease-in-out, transform 0.2s ease-in-out;
						-ms-transition: background-color 0.2s ease-in-out, transform 0.2s ease-in-out;
						transition: background-color 0.2s ease-in-out, transform 0.2s ease-in-out;
						content: '';
						display: block;
						position: absolute;
						top: 0.5rem;
						right: 0.5rem;
						width: 2.5rem;
						height: 2.5rem;
						border-radius: 50%;
						background-position: center;
						background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='20px' height='20px' viewBox='0 0 20 20' zoomAndPan='disable'%3E%3Cstyle%3Eline %7B stroke: %23ffffff%3B stroke-width: 2%3B %7D%3C/style%3E%3Cline x1='2' y1='2' x2='18' y2='18' /%3E%3Cline x1='18' y1='2' x2='2' y2='18' /%3E%3C/svg%3E");
						background-size: 18px 18px;
						background-repeat: no-repeat;
						pointer-events: none;
					}

					#main article .close:hover:before {
						background-color: rgba(255, 255, 255, 0.15);
						transform: rotate(90deg);
					}

					#main article .close:active:before {
						background-color: rgba(255, 255, 255, 0.25);
						transform: rotate(90deg) scale(0.95);
					}

			@media screen and (max-width: 736px) {

				#main article {
					padding: 3.5rem 2rem 1.5rem 2rem;
					border-radius: 8px;
				}

					#main article .close {
						top: 0.75rem;
						right: 0.75rem;
						width: 2.5rem;
						height: 2.5rem;
					}

					#main article .close:before {
						top: 0.25rem;
						right: 0.25rem;
						width: 2rem;
						height: 2rem;
						background-size: 14px 14px;
					}

			}

			@media screen and (max-width: 480px) {

				#main article {
					padding: 3rem 1.5rem 1.5rem 1.5rem;
					border-radius: 8px;
				}

			}

		/* Interactive Elements */
		.quiz-question,
		.matching-exercise,
		.expandable-section,
		.interactive-demo {
			margin: 2rem 0;
			padding: 2rem;
			background: rgba(255, 255, 255, 0.05);
			border: solid 1px rgba(255, 255, 255, 0.2);
			border-radius: 8px;
		}

		.quiz-question {
			margin-bottom: 1.5rem;
		}

		.quiz-question strong {
			display: block;
			margin-bottom: 1rem;
			font-size: 1.1rem;
			color: #ffffff;
		}

		.quiz-options {
			display: flex;
			flex-direction: column;
			gap: 0.75rem;
			margin-top: 1rem;
		}

		.quiz-options .choice {
			display: block;
			padding: 0.75rem 1rem;
			background: rgba(255, 255, 255, 0.05);
			border: solid 1px rgba(255, 255, 255, 0.2);
			border-radius: 4px;
			cursor: pointer;
			-moz-transition: background-color 0.2s ease-in-out, border-color 0.2s ease-in-out;
			-webkit-transition: background-color 0.2s ease-in-out, border-color 0.2s ease-in-out;
			-ms-transition: background-color 0.2s ease-in-out, border-color 0.2s ease-in-out;
			transition: background-color 0.2s ease-in-out, border-color 0.2s ease-in-out;
		}

		.quiz-options .choice:hover {
			background: rgba(255, 255, 255, 0.1);
			border-color: rgba(255, 255, 255, 0.4);
		}

		.quiz-options .choice.selected {
			background: rgba(255, 255, 255, 0.15);
			border-color: #ffffff;
		}

		.quiz-options .choice.correct {
			background: rgba(0, 255, 136, 0.2);
			border-color: #00ff88;
		}

		.quiz-options .choice.incorrect {
			background: rgba(255, 0, 0, 0.2);
			border-color: #ff0000;
		}

		.quiz-explanation {
			margin-top: 1rem;
			padding: 1rem;
			background: rgba(255, 255, 255, 0.05);
			border-radius: 4px;
			border-left: solid 3px rgba(255, 255, 255, 0.3);
		}

		.matching-exercise h4 {
			margin-bottom: 1rem;
		}

		.match-item {
			display: inline-block;
			padding: 0.75rem 1rem;
			margin: 0.5rem;
			background: rgba(255, 255, 255, 0.05);
			border: solid 1px rgba(255, 255, 255, 0.2);
			border-radius: 4px;
			cursor: pointer;
			-moz-transition: all 0.2s ease-in-out;
			-webkit-transition: all 0.2s ease-in-out;
			-ms-transition: all 0.2s ease-in-out;
			transition: all 0.2s ease-in-out;
		}

		.match-item:hover {
			background: rgba(255, 255, 255, 0.1);
			border-color: rgba(255, 255, 255, 0.4);
		}

		.match-item.selected {
			background: rgba(255, 255, 255, 0.15);
			border-color: #ffffff;
		}

		.match-item.matched {
			background: rgba(0, 255, 136, 0.2);
			border-color: #00ff88;
			cursor: default;
		}

		.expandable-section {
			margin: 2rem 0;
		}

		.expandable-header {
			display: flex;
			justify-content: space-between;
			align-items: center;
			padding: 1rem;
			background: rgba(255, 255, 255, 0.05);
			border: solid 1px rgba(255, 255, 255, 0.2);
			border-radius: 4px;
			cursor: pointer;
			-moz-transition: background-color 0.2s ease-in-out;
			-webkit-transition: background-color 0.2s ease-in-out;
			-ms-transition: background-color 0.2s ease-in-out;
			transition: background-color 0.2s ease-in-out;
		}

		.expandable-header:hover {
			background: rgba(255, 255, 255, 0.1);
		}

		.expandable-header h5 {
			margin: 0;
			flex: 1;
		}

		.expand-icon {
			-moz-transition: transform 0.3s ease-in-out;
			-webkit-transition: transform 0.3s ease-in-out;
			-ms-transition: transform 0.3s ease-in-out;
			transition: transform 0.3s ease-in-out;
			font-size: 0.8rem;
		}

		.expandable-section.expanded .expand-icon {
			transform: rotate(180deg);
		}

		.expandable-content {
			display: none;
			padding: 1rem;
			margin-top: 0.5rem;
			background: rgba(255, 255, 255, 0.03);
			border-radius: 4px;
		}

		.expandable-section.expanded .expandable-content {
			display: block;
		}

		.interactive-demo {
			margin: 2rem 0;
		}

		.interactive-demo h5 {
			margin-bottom: 1rem;
		}

		.code-editor {
			background: rgba(0, 0, 0, 0.3);
			border: solid 1px rgba(255, 255, 255, 0.2);
			border-radius: 4px;
			padding: 1rem;
			overflow-x: auto;
		}

		.code-editor pre {
			margin: 0;
			font-family: "Courier New", monospace;
			font-size: 0.9rem;
			line-height: 1.5;
		}

		.output-box {
			margin-top: 1rem;
			padding: 1rem;
			background: rgba(255, 255, 255, 0.05);
			border: solid 1px rgba(255, 255, 255, 0.2);
			border-radius: 4px;
		}

		/* Footer */
		#footer {
			-moz-transition: -moz-transform 0.325s ease-in-out, -moz-filter 0.325s ease-in-out, opacity 0.325s ease-in-out;
			-webkit-transition: -webkit-transform 0.325s ease-in-out, -webkit-filter 0.325s ease-in-out, opacity 0.325s ease-in-out;
			-ms-transition: -ms-transform 0.325s ease-in-out, -ms-filter 0.325s ease-in-out, opacity 0.325s ease-in-out;
			transition: transform 0.325s ease-in-out, filter 0.325s ease-in-out, opacity 0.325s ease-in-out;
			width: 100%;
			max-width: 100%;
			margin-top: 2rem;
			text-align: center;
		}

			#footer .copyright {
				letter-spacing: 0.2rem;
				font-size: 0.6rem;
				opacity: 0.75;
				margin-bottom: 0;
				text-transform: uppercase;
			}

			body.is-article-visible #footer {
				-moz-transform: scale(0.95);
				-webkit-transform: scale(0.95);
				-ms-transform: scale(0.95);
				transform: scale(0.95);
				-moz-filter: blur(0.1rem);
				-webkit-filter: blur(0.1rem);
				-ms-filter: blur(0.1rem);
				filter: blur(0.1rem);
				opacity: 0;
			}

			body.is-preload #footer {
				opacity: 0.3;
			}`;

  return cssContent;
}

/**
 * Generates noscript CSS
 */
function generateDimensionNoscriptCSS(): string {
  return `/* Noscript CSS */
		body.is-preload #bg:before { background-color: transparent; }
		body.is-preload #header { filter: none; }
		body.is-preload #header > * { opacity: 1; }
		body.is-preload #header .content .inner { max-height: none; padding: 3rem 2rem; opacity: 1; }
		#main article { opacity: 1; margin: 4rem 0 0 0; }`;
}

/**
 * Generates JavaScript for dimension template
 * Embeds the full JavaScript from main.js
 */
function generateDimensionJS(): string {
  return `/*
	Dimension by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
*/

(function($) {

	var	$window = $(window),
		$body = $('body'),
		$wrapper = $('#wrapper'),
		$header = $('#header'),
		$footer = $('#footer'),
		$main = $('#main'),
		$main_articles = $main.children('article');

	// Breakpoints.
		breakpoints({
			xlarge:   [ '1281px',  '1680px' ],
			large:    [ '981px',   '1280px' ],
			medium:   [ '737px',   '980px'  ],
			small:    [ '481px',   '736px'  ],
			xsmall:   [ '361px',   '480px'  ],
			xxsmall:  [ null,      '360px'  ]
		});

	// Play initial animations on page load.
		$window.on('load', function() {
			window.setTimeout(function() {
				$body.removeClass('is-preload');
			}, 100);
		});

	// Fix: Flexbox min-height bug on IE.
		if (browser.name == 'ie') {

			var flexboxFixTimeoutId;

			$window.on('resize.flexbox-fix', function() {

				clearTimeout(flexboxFixTimeoutId);

				flexboxFixTimeoutId = setTimeout(function() {

					if ($wrapper.prop('scrollHeight') > $window.height())
						$wrapper.css('height', 'auto');
					else
						$wrapper.css('height', '100vh');

				}, 250);

			}).triggerHandler('resize.flexbox-fix');

		}

	// Nav.
		var $nav = $header.children('nav'),
			$nav_li = $nav.find('li'),
			$nav_links = $nav.find('a');

		// Add "middle" alignment classes if we're dealing with an even number of items.
			if ($nav_li.length % 2 == 0) {

				$nav.addClass('use-middle');
				$nav_li.eq( ($nav_li.length / 2) ).addClass('is-middle');

			}

		// Handle navigation link clicks.
			$nav_links.on('click', function(event) {
				var href = $(this).attr('href');
				if (href && href.indexOf('#') === 0) {
					event.preventDefault();
					event.stopPropagation();
					var id = href.substr(1);
					if ($main_articles.filter('#' + id).length > 0) {
						$main._show(id);
					}
				}
			});

	// Main.
		var	delay = 325,
			locked = false;

	// #region agent log
	fetch('http://127.0.0.1:7244/ingest/4a8f7e76-eb40-4f86-bc5b-2864f3e0791c',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({location:'dimensionTemplate.ts:1698',message:'Defining $main._show',data:{mainExists:typeof $main !== 'undefined'},timestamp:Date.now(),sessionId:'debug-session',runId:'run1',hypothesisId:'A'})}).catch(()=>{});
	// #endregion

	// Methods.
		$main._show = function(id, initial) {

				var $article = $main_articles.filter('#' + id);

				// No such article? Bail.
					if ($article.length == 0)
						return;

				// Handle lock.

					// Already locked? Speed through "show" steps w/o delays.
						if (locked || (typeof initial != 'undefined' && initial === true)) {

							// Mark as switching.
								$body.addClass('is-switching');

							// Mark as visible.
								$body.addClass('is-article-visible');

							// Deactivate all articles (just in case one's already active).
								$main_articles.removeClass('active');

							// Hide header, footer.
								$header.hide();
								$footer.hide();

							// Show main, article.
								$main.show();
								$article.show();

							// Activate article.
								$article.addClass('active');

							// Unlock.
								locked = false;

							// Unmark as switching.
								setTimeout(function() {
									$body.removeClass('is-switching');
								}, (initial ? 1000 : 0));

							return;

						}

					// Lock.
						locked = true;

				// Article already visible? Just swap articles.
					if ($body.hasClass('is-article-visible')) {

						// Deactivate current article.
							var $currentArticle = $main_articles.filter('.active');

							$currentArticle.removeClass('active');

						// Show article.
							setTimeout(function() {

								// Hide current article.
									$currentArticle.hide();

								// Show article.
									$article.show();

								// Activate article.
									setTimeout(function() {

										$article.addClass('active');

										// Window stuff.
											$window
												.scrollTop(0)
												.triggerHandler('resize.flexbox-fix');

										// Unlock.
											setTimeout(function() {
												locked = false;
											}, delay);

									}, 25);

							}, delay);

					}

				// Otherwise, handle as normal.
					else {

						// Mark as visible.
							$body
								.addClass('is-article-visible');

						// Show article.
							setTimeout(function() {

								// Hide header, footer.
									$header.hide();
									$footer.hide();

								// Show main, article.
									$main.show();
									$article.show();

								// Activate article.
									setTimeout(function() {

										$article.addClass('active');

										// Window stuff.
											$window
												.scrollTop(0)
												.triggerHandler('resize.flexbox-fix');

										// Unlock.
											setTimeout(function() {
												locked = false;
											}, delay);

									}, 25);

							}, delay);

					}

			};

	// #region agent log
	fetch('http://127.0.0.1:7244/ingest/4a8f7e76-eb40-4f86-bc5b-2864f3e0791c',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({location:'dimensionTemplate.ts:1829',message:'Defining $main._hide',data:{mainExists:typeof $main !== 'undefined'},timestamp:Date.now(),sessionId:'debug-session',runId:'run1',hypothesisId:'A'})}).catch(()=>{});
	// #endregion

			$main._hide = function(addState) {

				var $article = $main_articles.filter('.active');

				// Article not visible? Bail.
					if (!$body.hasClass('is-article-visible'))
						return;

				// Add state?
					if (typeof addState != 'undefined'
					&&	addState === true)
						history.pushState(null, null, '#');

				// Handle lock.

					// Already locked? Speed through "hide" steps w/o delays.
						if (locked) {

							// Mark as switching.
								$body.addClass('is-switching');

							// Deactivate article.
								$article.removeClass('active');

							// Hide article, main.
								$article.hide();
								$main.hide();

							// Show footer, header.
								$footer.show();
								$header.show();

							// Unmark as visible.
								$body.removeClass('is-article-visible');

							// Unlock.
								locked = false;

							// Unmark as switching.
								$body.removeClass('is-switching');

							// Window stuff.
								$window
									.scrollTop(0)
									.triggerHandler('resize.flexbox-fix');

							return;

						}

					// Lock.
						locked = true;

				// Deactivate article.
					$article.removeClass('active');

				// Hide article.
					setTimeout(function() {

						// Hide article, main.
							$article.hide();
							$main.hide();

						// Show footer, header.
							$footer.show();
							$header.show();

						// Unmark as visible.
							setTimeout(function() {

								$body.removeClass('is-article-visible');

								// Window stuff.
									$window
										.scrollTop(0)
										.triggerHandler('resize.flexbox-fix');

								// Unlock.
									setTimeout(function() {
										locked = false;
									}, delay);

							}, 25);

					}, delay);


			};

		// Articles.
			$main_articles.each(function() {

				var $this = $(this);

				// Prevent clicks from inside article from bubbling (except close button).
				// IMPORTANT: Attach this handler FIRST, before creating close button
				// This ensures the close button check works correctly
				// Use native addEventListener with capture phase for better iframe compatibility
					if ($this[0]) {
						$this[0].addEventListener('click', function(event) {
							// Don't stop propagation for close button clicks or clicks outside article
							// Check multiple ways to detect close button clicks
							var target = event.target;
							var isCloseButton = (target.closest && target.closest('.close') !== null) ||
							                    (target.classList && target.classList.contains('close')) ||
							                    (target.parentElement && target.parentElement.classList && target.parentElement.classList.contains('close')) ||
							                    ($(target).closest('.close').length > 0);
							
							// Check if click originated from within this article
							var isWithinArticle = $this[0].contains(target);
							
							console.log('Article click handler (capture) - target:', target, 'isCloseButton:', isCloseButton, 'isWithinArticle:', isWithinArticle);
							
							// Only stop propagation if:
							// 1. Click is within the article
							// 2. Click is NOT on the close button
							if (isWithinArticle && !isCloseButton) {
								event.stopPropagation();
							} else {
								console.log('Article click handler - allowing click to propagate (close button or outside article)');
								// Don't stop propagation for close button or clicks outside article
							}
						}, true); // Use capture phase for better iframe compatibility
					}

				// Close button - only add if it doesn't exist
					if ($this.find('.close').length === 0) {
						var $closeBtn = $('<div class="close">Close</div>');
						$this.prepend($closeBtn);
						
						console.log('Close button created for article:', $this.attr('id'), 'Button exists:', $closeBtn.length > 0);
						
						// Use multiple event handlers to ensure we catch the click
						// Handler 1: Direct click on close button
						// Use native addEventListener with capture phase for better iframe compatibility
						if ($closeBtn[0]) {
							$closeBtn[0].addEventListener('click', function(event) {
								console.log('Close button click handler (native capture) fired', event.target, event.currentTarget);
								event.preventDefault();
								event.stopPropagation();
								event.stopImmediatePropagation();
								
								// Call hide function directly
								if (typeof $main !== 'undefined' && typeof $main._hide === 'function') {
									console.log('Calling $main._hide(true)');
									$main._hide(true);
								} else {
									console.log('$main._hide not available, using fallback');
									// Fallback: hide manually
									$body.removeClass('is-article-visible');
									$main.hide();
									$main_articles.hide();
									$header.show();
									$footer.show();
									history.pushState(null, null, '#');
								}
								return false;
							}, true); // Capture phase for highest priority in iframe
						}
						
						// Also attach jQuery handler as backup
						$closeBtn.on('click.closeBtn', function(event) {
							console.log('Close button click handler (jQuery) fired', event.target, event.currentTarget);
							event.preventDefault();
							event.stopPropagation();
							event.stopImmediatePropagation();
							
							// Call hide function directly
							if (typeof $main !== 'undefined' && typeof $main._hide === 'function') {
								console.log('Calling $main._hide(true)');
								$main._hide(true);
							} else {
								console.log('$main._hide not available, using fallback');
								// Fallback: hide manually
								$body.removeClass('is-article-visible');
								$main.hide();
								$main_articles.hide();
								$header.show();
								$footer.show();
								history.pushState(null, null, '#');
							}
							return false;
						});
						
						// Handler 2: Mousedown as backup
						$closeBtn.on('mousedown.closeBtn', function(event) {
							console.log('Close button mousedown handler fired');
							event.preventDefault();
							event.stopPropagation();
							return false;
						});
						
						// Handler 3: Event delegation on article (fallback)
						$this.off('click.closeBtnDelegated').on('click.closeBtnDelegated', '.close', function(event) {
							console.log('Delegated close button click handler fired');
							event.preventDefault();
							event.stopPropagation();
							event.stopImmediatePropagation();
							
							if (typeof $main !== 'undefined' && typeof $main._hide === 'function') {
								$main._hide(true);
							} else {
								$body.removeClass('is-article-visible');
								$main.hide();
								$main_articles.hide();
								$header.show();
								$footer.show();
								history.pushState(null, null, '#');
							}
							return false;
						});
						
						// Handler 4: Document-level delegation as ultimate fallback
						var articleId = $this.attr('id');
						$(document).off('click.closeBtnDoc_' + articleId).on('click.closeBtnDoc_' + articleId, '#' + articleId + ' > .close', function(event) {
							console.log('Document-level delegated close button click handler fired');
							event.preventDefault();
							event.stopPropagation();
							event.stopImmediatePropagation();
							
							if (typeof $main !== 'undefined' && typeof $main._hide === 'function') {
								$main._hide(true);
							} else {
								$body.removeClass('is-article-visible');
								$main.hide();
								$main_articles.hide();
								$header.show();
								$footer.show();
								history.pushState(null, null, '#');
							}
							return false;
						});
						
						// Handler 3: Use event delegation on the article as fallback
						$this.off('click.closeBtnDelegated').on('click.closeBtnDelegated', '.close', function(event) {
							console.log('Delegated close button click handler fired');
							event.preventDefault();
							event.stopPropagation();
							event.stopImmediatePropagation();
							
							if (typeof $main !== 'undefined' && typeof $main._hide === 'function') {
								$main._hide(true);
							} else {
								$body.removeClass('is-article-visible');
								$main.hide();
								$main_articles.hide();
								$header.show();
								$footer.show();
								history.pushState(null, null, '#');
							}
							return false;
						});
					}

			});

		// Detect if we're in an iframe
			var isInIframe = (window.self !== window.top);
			console.log('Running in iframe:', isInIframe);

		// Events - Click outside to close
		// Use multiple approaches for iframe compatibility
			// Approach 1: Body click handler
			$body.on('click.closeOutside', function(event) {
				// Enhanced close button detection for iframe contexts
				var $target = $(event.target);
				var target = event.target;
				var isNav = $target.closest('nav').length > 0;
				var isClose = $target.closest('.close').length > 0 || 
				              $target.hasClass('close') ||
				              $target.parent().hasClass('close') ||
				              (target.classList && target.classList.contains('close'));
				var isArticle = $target.closest('article').length > 0 || 
				                $target.closest('#main article').length > 0;
				
				console.log('Body click handler - target:', target, 'isClose:', isClose, 'isNav:', isNav, 'isArticle:', isArticle);

				// Don't hide if clicking on navigation links, close button, or inside article
					if (isNav || isClose || isArticle) {
						if (isClose) console.log('Body click handler - ignoring close button click');
						if (isArticle) console.log('Body click handler - ignoring article click');
						return;
					}

				// Article visible? Hide when clicking outside (on body or main backdrop)
					if ($body.hasClass('is-article-visible')) {
						console.log('Body click handler - closing article (clicked outside)');
						$main._hide(true);
					}
			});
			
			// Approach 2: Click on #main backdrop (the area around articles)
			$main.on('click.closeOutside', function(event) {
				var $target = $(event.target);
				// Only close if clicking directly on #main (not on article or its children)
				if ($target.is('#main') && !$target.closest('article').length) {
					console.log('Main backdrop clicked - closing article');
					if ($body.hasClass('is-article-visible')) {
						$main._hide(true);
					}
				}
			});
			
			// Approach 3: Native addEventListener for better iframe support
			if (document.body) {
				document.body.addEventListener('click', function(event) {
					var target = event.target;
					// Check if click is outside article
					var article = target.closest('article');
					var nav = target.closest('nav');
					var closeBtn = target.closest('.close') || (target.classList && target.classList.contains('close'));
					
					// Only close if clicking outside article, nav, and close button
					if (!article && !nav && !closeBtn && document.body.classList.contains('is-article-visible')) {
						console.log('Native body click handler - closing article (clicked outside)');
						if (typeof $main !== 'undefined' && typeof $main._hide === 'function') {
							$main._hide(true);
						}
					}
				}, true); // Use capture phase
			}

			// Escape key handler - Multiple approaches for iframe compatibility
			// Approach 1: jQuery keyup
			$window.on('keyup.escapeClose', function(event) {
				if (event.keyCode === 27 || event.key === 'Escape' || event.key === 'Esc') {
					console.log('Escape key pressed (jQuery)');
					if ($body.hasClass('is-article-visible')) {
						console.log('Closing article via Escape key');
						$main._hide(true);
					}
				}
			});
			
			// Approach 2: Native addEventListener for better iframe support
			if (window) {
				window.addEventListener('keydown', function(event) {
					if (event.key === 'Escape' || event.key === 'Esc' || event.keyCode === 27) {
						console.log('Escape key pressed (native)');
						if (document.body.classList.contains('is-article-visible')) {
							console.log('Closing article via Escape key (native)');
							event.preventDefault();
							if (typeof $main !== 'undefined' && typeof $main._hide === 'function') {
								$main._hide(true);
							} else {
								// Fallback
								document.body.classList.remove('is-article-visible');
								var main = document.getElementById('main');
								var articles = main ? main.querySelectorAll('article') : [];
								var header = document.getElementById('header');
								var footer = document.getElementById('footer');
								if (main) main.style.display = 'none';
								articles.forEach(function(article) { article.style.display = 'none'; });
								if (header) header.style.display = '';
								if (footer) footer.style.display = '';
								history.pushState(null, null, '#');
							}
						}
					}
				}, true); // Use capture phase
				
				// Also listen for keyup as backup
				window.addEventListener('keyup', function(event) {
					if (event.key === 'Escape' || event.key === 'Esc' || event.keyCode === 27) {
						console.log('Escape key released (native)');
						if (document.body.classList.contains('is-article-visible')) {
							console.log('Closing article via Escape key (native keyup)');
							event.preventDefault();
							if (typeof $main !== 'undefined' && typeof $main._hide === 'function') {
								$main._hide(true);
							}
						}
					}
				}, true);
			}

			$window.on('hashchange', function(event) {

				// Empty hash?
					if (location.hash == ''
					||	location.hash == '#') {

						// Prevent default.
							event.preventDefault();
							event.stopPropagation();

						// Hide.
							$main._hide();

					}

				// Otherwise, check for a matching article.
					else {
						var hashId = location.hash.substr(1);
						if ($main_articles.filter('#' + hashId).length > 0) {

							// Prevent default.
								event.preventDefault();
								event.stopPropagation();

							// Show article.
								$main._show(hashId);

						}
					}

			});

		// Scroll restoration.
		// This prevents the page from scrolling back to the top on a hashchange.
			if ('scrollRestoration' in history)
				history.scrollRestoration = 'manual';
			else {

				var	oldScrollPos = 0,
					scrollPos = 0,
					$htmlbody = $('html,body');

				$window
					.on('scroll', function() {

						oldScrollPos = scrollPos;
						scrollPos = $htmlbody.scrollTop();

					})
					.on('hashchange', function() {
						$window.scrollTop(oldScrollPos);
					});

			}

		// Initialize.

			// Hide main, articles.
				$main.hide();
				$main_articles.hide();

			// Initial article.
				if (location.hash != ''
				&&	location.hash != '#')
					$window.on('load', function() {
						$main._show(location.hash.substr(1), true);
					});

})(jQuery);`;
}

